name: Fourth Lab

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NAME: 'Жидков Александр Владимирович'
      GROUP: 'М3111'

    steps:
      - name: Info
        run: |
          echo "Name: ${{ env.NAME }}"
          echo "Group: ${{ env.GROUP }}"
          echo "Nickname: ${{ github.actor }}"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit Tests
        run: |
          python -m unittest discover -s tests

      - name: Style Check
        run: |
          flake8 .